export const AUTH = {
    AUTH_REQUEST: 'AUTH_REQUEST',
    AUTH_SUCCESS: 'AUTH_SUCCESS',
    AUTH_ERROR: 'AUTH_ERROR',

    SIGNOUT_USER: 'SIGNOUT_USER'
}

export const ORGANIZATION = {
    FETCH_ORG_REQUEST: 'FETCH_ORG_REQUEST',
    FETCH_ORG_SUCCESS: 'FETCH_ORG_SUCCESS',
    FETCH_ORG_ERROR: 'FETCH_ORG_ERROR',

    ADD_ORG_REQUEST: 'ADD_ORG_REQUEST',
    ADD_ORG_SUCCESS: 'ADD_ORG_SUCCESS',
    ADD_ORG_ERROR: 'ADD_ORG_ERROR',

    EDIT_ORG_REQUEST: 'EDIT_ORG_REQUEST',
    EDIT_ORG_SUCCESS: 'EDIT_ORG_SUCCESS',
    EDIT_ORG_ERROR: 'EDIT_ORG_ERROR',

    CLEAR_ORG_ERRORS: 'CLEAR_ORG_ERRORS'
}

export const SECTIONS = {
    SECTIONS_REQUEST: 'SECTIONS_REQUEST',
    SECTIONS_SUCCESS: 'SECTIONS_SUCCESS',
    SECTIONS_ERROR: 'SECTIONS_ERROR',

    ADD_SECTION_REQUEST: 'ADD_SECTION_REQUEST',
    ADD_SECTION_SUCCESS: 'ADD_SECTION_SUCCESS',
    ADD_SECTION_ERROR: 'ADD_SECTION_ERROR',

    DELETE_SECTION_SUCCESS: 'DELETE_SECTION_SUCCESS',
    DELETE_SECTION_ERROR: 'DELETE_SECTION_ERROR',

    CLEAR_SECTION_ERRORS: 'CLEAR_SECTION_ERRORS'
}

export const CATEGORIES = {
    CATEGORIES_REQUEST: 'CATEGORIES_REQUEST',
    CATEGORIES_SUCCESS: 'CATEGORIES_SUCCESS',
    CATEGORIES_ERROR: 'CATEGORIES_ERROR',

    ADD_CATEGORY_REQUEST: 'ADD_CATEGORY_REQUEST',
    ADD_CATEGORY_SUCCESS: 'ADD_CATEGORY_SUCCESS',
    ADD_CATEGORY_ERROR: 'ADD_CATEGORY_ERROR',

    DELETE_CATEGORY_SUCCESS: 'DELETE_CATEGORY_SUCCESS',
    DELETE_CATEGORY_ERROR: 'DELETE_CATEGORY_ERROR',

    CLEAR_CATEGORY_ERRORS: 'CLEAR_CATEGORY_ERRORS'
}

export const PRODUCTS = {
    PRODUCTS_REQUEST: 'PRODUCTS_REQUEST',
    PRODUCTS_SUCCESS: 'PRODUCTS_SUCCESS',
    PRODUCTS_ERROR: 'PRODUCTS_ERROR',

    ADD_PRODUCT_REQUEST: 'ADD_PRODUCT_REQUEST',
    ADD_PRODUCT_SUCCESS: 'ADD_PRODUCT_SUCCESS',
    ADD_PRODUCT_ERROR: 'ADD_PRODUCT_ERROR',

    EDIT_PRODUCT_REQUEST: 'EDIT_PRODUCT_REQUEST',
    EDIT_PRODUCT_SUCCESS: 'EDIT_PRODUCT_SUCCESS',

    DELETE_PRODUCT_SUCCESS: 'DELETE_PRODUCT_SUCCESS',
    DELETE_PRODUCT_ERROR: 'DELETE_PRODUCT_ERROR',

    CLEAR_PRODUCT_ERRORS: 'CLEAR_PRODUCT_ERRORS'
}

export const ORDERS = {
    ORDERS_REQUEST: 'ORDERS_REQUEST',
    ORDERS_SUCCESS: 'ORDERS_SUCCESS',
    ORDERS_ERROR: 'ORDERS_ERROR',

    FETCH_ORDER_REQUEST: 'FETCH_ORDER_REQUEST',
    FETCH_ORDER_SUCCESS: 'FETCH_ORDER_SUCCESS',
    FETCH_ORDER_ERROR: 'FETCH_ORDER_ERROR',

    CLEAR_ORDER_ERRORS: 'CLEAR_ORDER_ERRORS'
}

export const OFFERS = {
    FETCH_OFFER_REQUEST: 'FETCH_OFFER_REQUEST',
    FETCH_OFFER_SUCCESS: 'FETCH_OFFER_SUCCESS',
    FETCH_OFFER_ERROR: 'FETCH_OFFER_ERROR',

    ADD_OFFER_REQUEST: 'ADD_OFFER_REQUEST',
    ADD_OFFER_SUCCESS: 'ADD_OFFER_SUCCESS',
    ADD_OFFER_ERROR: 'ADD_OFFER_ERROR',

    DELETE_OFFER_REQUEST: 'DELETE_OFFER_REQUEST',
    DELETE_OFFER_SUCCESS: 'DELETE_OFFER_SUCCESS',
    DELETE_OFFER_ERROR: 'DELETE_OFFER_ERROR',

    CLEAR_OFFER_ERROR: 'CLEAR_OFFER_ERROR'
}
