version: "3"
services:
  oshop-api:
    container_name: oshop-api
    restart: unless-stopped
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    env_file: ./backend/.env
    environment:
      - NODE_ENV=production
  oshop-admin:
    container_name: oshop-admin
    restart: unless-stopped
    build:
      context: ./oshop-admin
      dockerfile: Dockerfile
    environment:
      - NODE_PATH=/app/src
    ports:
      - '3001:81'
  oshop-client:
    container_name: oshop-client
    restart: unless-stopped
    build:
      context: ./client-side
      dockerfile: Dockerfile
    env_file: ./client-side/.env.local
    environment:
      - NODE_PATH=/app
    ports:
      - '3000:80'