version: "3"
services:
  api:
    container_name: savana-api
    restart: unless-stopped
    image: evanshango/savana_api

#    build:
#      context: ./backend
#      dockerfile: Dockerfile
    ports:
      - '5000:5000'
#    env_file:
#      - ./backend/.env
#    environment:
#      - NODE_ENV=production
#      - NODE_PATH=/build/src
  admin:
    container_name: savana-admin
    restart: unless-stopped
    build:
      context: ./oshop-admin
      dockerfile: Dockerfile
    environment:
      - NODE_PATH=/app/src
    ports:
      - '3001:80'
    depends_on:
      - api
  client:
    container_name: savana-client
    restart: unless-stopped
    build:
      context: ./savana-client
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - NODE_PATH=/app/src
    ports:
      - '3000:80'
    depends_on:
      - api