version: "3.7"
services:
  api:
    container_name: oshop-api
    restart: unless-stopped
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: production
    ports:
      - '5000:5000'
#    command: node build/index.js
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=production
      - NODE_PATH=/build/src
  admin:
    container_name: oshop-admin
    restart: unless-stopped
    build:
      context: ./oshop-admin
      dockerfile: Dockerfile
    environment:
      - NODE_PATH=/app/src
    ports:
      - '3001:3001'
    depends_on:
      - api
  client:
    container_name: savana-client
    restart: unless-stopped
    build:
      context: ./savana-client
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - NODE_PATH=/app/src
    ports:
      - '3000:3000'
    depends_on:
      - api