version: "3"
services:
  api:
    container_name: savana-api
    restart: unless-stopped
    image: evanshango/savana_api
    network_mode: "host"
    ports:
      - '5000:5000'
  admin:
    container_name: savana-admin
    restart: unless-stopped
    image: evanshango/savana_admin
    ports:
      - '3001:80'
    depends_on:
      - api
  client:
    container_name: savana-client
    restart: unless-stopped
    image: evanshango/savana_client
    ports:
      - '3000:80'
    depends_on:
      - api