version: "3"
services:
  client:
    container_name: oshop-client
    restart: unless-stopped
    build:
      context: ./client-side
      dockerfile: Dockerfile
    env_file: ./client-side/.env.local
    environment:
      - NODE_PATH=/app
    ports:
      - '3000:80'
#    depends_on:
#      - api