export const AUTH = {
    AUTH_REQUEST: 'AUTH_REQUEST',
    AUTH_SUCCESS: 'AUTH_SUCCESS',
    AUTH_ERROR: 'AUTH_ERROR'
}

export const USER = {
    USER_REQUEST: 'USER_REQUEST',
    USER_SUCCESS: 'USER_SUCCESS',
    USER_ERROR: 'USER_ERROR',
}

export const CART = {
    FETCH_CART_ITEMS: 'FETCH_CART_ITEMS',
    ADD_ITEM_TO_CART: 'ADD_ITEM_TO_CART',
    UPDATE_CART_UNITS: 'UPDATE_CART_UNITS',
    DELETE_CART_ITEM: 'DELETE_CART_ITEM'
}