export const AUTH = {
    AUTH_REQUEST: 'AUTH_REQUEST',
    AUTH_SUCCESS: 'AUTH_SUCCESS',
    AUTH_ERROR: 'AUTH_ERROR',

    CLEAR_AUTH_ERRORS: 'CLEAR_AUTH_ERRORS',
}

export const USER = {
    USER_REQUEST: 'USER_REQUEST',
    USER_SUCCESS: 'USER_SUCCESS',
    USER_ERROR: 'USER_ERROR',
}

export const SECTIONS = {
    SECTIONS_REQUEST: 'SECTIONS_REQUEST',
    SECTIONS_SUCCESS: 'SECTIONS_SUCCESS',
    SECTIONS_ERROR: 'SECTIONS_ERROR',

    CLEAR_SECTION_ERRORS: 'CLEAR_SECTION_ERRORS'
}

export const PRODUCTS = {
    FETCH_PRODUCTS_REQUEST: 'FETCH_PRODUCTS_REQUEST',
    FETCH_PRODUCTS_SUCCESS: 'FETCH_PRODUCTS_SUCCESS',
    FETCH_PRODUCTS_ERROR: 'FETCH_PRODUCTS_ERROR',

    CLEAR_PRODUCT_ERRORS: 'CLEAR_PRODUCT_ERRORS'
}

export const CART = {
    FETCH_CART_REQUEST: 'FETCH_CART_REQUEST',
    FETCH_CART_SUCCESS: 'FETCH_CART_SUCCESS',
    FETCH_CART_ERROR: 'FETCH_CART_ERROR',

    ADD_ITEM_TO_CART_REQUEST: 'ADD_ITEM_TO_CART_REQUEST',
    ADD_ITEM_TO_CART_SUCCESS: 'ADD_ITEM_TO_CART_SUCCESS',
    ADD_ITEM_TO_CART_ERROR: 'ADD_ITEM_TO_CART_ERROR',

    UPDATE_CART_UNITS_REQUEST: 'UPDATE_CART_UNITS_REQUEST',
    UPDATE_CART_UNITS_SUCCESS: 'UPDATE_CART_UNITS_SUCCESS',
    UPDATE_CART_UNITS_ERROR: 'UPDATE_CART_UNITS_ERROR',

    DELETE_CART_ITEM_REQUEST: 'DELETE_CART_ITEM_REQUEST',
    DELETE_CART_ITEM_SUCCESS: 'DELETE_CART_ITEM_SUCCESS',
    DELETE_CART_ITEM_ERROR: 'DELETE_CART_ITEM_ERROR',

    CLEAR_CART_ERRORS: 'CLEAR_CART_ERRORS'
}