export const AUTH = {
    AUTH_REQUEST: 'AUTH_REQUEST',
    AUTH_SUCCESS: 'AUTH_SUCCESS',
    AUTH_ERROR: 'AUTH_ERROR',

    CLEAR_AUTH_ERRORS: 'CLEAR_AUTH_ERRORS',
}

export const USER = {
    FETCH_USER_REQUEST: 'FETCH_USER_REQUEST',
    FETCH_USER_SUCCESS: 'FETCH_USER_SUCCESS',
    FETCH_USER_ERROR: 'FETCH_USER_ERROR',

    CLEAR_USER_ERROR: 'CLEAR_USER_ERROR'
}

export const SECTIONS = {
    SECTIONS_REQUEST: 'SECTIONS_REQUEST',
    SECTIONS_SUCCESS: 'SECTIONS_SUCCESS',
    SECTIONS_ERROR: 'SECTIONS_ERROR',

    CLEAR_SECTION_ERRORS: 'CLEAR_SECTION_ERRORS'
}

export const PRODUCTS = {
    FETCH_PRODUCTS_REQUEST: 'FETCH_PRODUCTS_REQUEST',
    FETCH_PRODUCTS_SUCCESS: 'FETCH_PRODUCTS_SUCCESS',
    FETCH_PRODUCTS_ERROR: 'FETCH_PRODUCTS_ERROR',

    CLEAR_PRODUCT_ERRORS: 'CLEAR_PRODUCT_ERRORS'
}

export const ADDRESSES = {
    FETCH_ADDRESS_REQUEST: 'FETCH_ADDRESS_REQUEST',
    FETCH_ADDRESS_SUCCESS: 'FETCH_ADDRESS_SUCCESS',
    FETCH_ADDRESS_ERROR: 'FETCH_ADDRESS_ERROR',

    ADD_ADDRESS_REQUEST: 'ADD_ADDRESS_REQUEST',
    ADD_ADDRESS_SUCCESS: 'ADD_ADDRESS_SUCCESS',
    ADD_ADDRESS_ERROR: 'ADD_ADDRESS_ERROR',

    CLEAR_ADDRESS_ERROR: 'CLEAR_ADDRESS_ERROR'
}

export const CART = {
    FETCH_CART_REQUEST: 'FETCH_CART_REQUEST',
    FETCH_CART_SUCCESS: 'FETCH_CART_SUCCESS',
    FETCH_CART_ERROR: 'FETCH_CART_ERROR',

    ADD_ITEM_TO_CART_REQUEST: 'ADD_ITEM_TO_CART_REQUEST',
    ADD_ITEM_TO_CART_SUCCESS: 'ADD_ITEM_TO_CART_SUCCESS',
    ADD_ITEM_TO_CART_ERROR: 'ADD_ITEM_TO_CART_ERROR',

    UPDATE_CART_UNITS_REQUEST: 'UPDATE_CART_UNITS_REQUEST',
    UPDATE_CART_UNITS_SUCCESS: 'UPDATE_CART_UNITS_SUCCESS',
    UPDATE_CART_UNITS_ERROR: 'UPDATE_CART_UNITS_ERROR',

    DELETE_CART_ITEM_REQUEST: 'DELETE_CART_ITEM_REQUEST',
    DELETE_CART_ITEM_SUCCESS: 'DELETE_CART_ITEM_SUCCESS',
    DELETE_CART_ITEM_ERROR: 'DELETE_CART_ITEM_ERROR',

    CLEAR_CART_ITEMS: 'CLEAR_CART_ITEMS',
    CLEAR_CART_ERRORS: 'CLEAR_CART_ERRORS'
}

export const ORDER = {
    FETCH_ORDERS_REQUEST: 'FETCH_ORDERS_REQUEST',
    FETCH_ORDERS_SUCCESS: 'FETCH_ORDERS_SUCCESS',
    FETCH_ORDERS_ERROR: 'FETCH_ORDERS_ERROR',

    ADD_ORDER_REQUEST: 'ADD_ORDER_REQUEST',
    ADD_ORDER_SUCCESS: 'ADD_ORDER_SUCCESS',
    ADD_ORDER_ERROR: 'ADD_ORDER_ERROR',

    CLEAR_NEW_ORDER: 'CLEAR_NEW_ORDER',
    CLEAR_ORDER_ERRORS: 'CLEAR_ORDERS_ERRORS'
}

export const CHECKOUT = {
    ADD_PARAM: 'ADD_PARAM'
}

export const OFFERS = {
    FETCH_OFFERS_REQUEST: 'FETCH_OFFERS_REQUEST',
    FETCH_OFFERS_SUCCESS: 'FETCH_OFFERS_SUCCESS',
    FETCH_OFFERS_ERROR: 'FETCH_OFFERS_ERROR',

    CLEAR_OFFERS_ERROR: 'CLEAR_OFFERS_ERROR'
}

export const PRODUCT = {
    FETCH_PRODUCT_REQUEST: 'FETCH_PRODUCT_REQUEST',
    FETCH_PRODUCT_SUCCESS: 'FETCH_PRODUCT_SUCCESS',
    FETCH_PRODUCT_ERROR: 'FETCH_PRODUCT_ERROR',

    CLEAR_PRODUCT_ERROR: 'CLEAR_PRODUCT_ERROR',
}

export const PAYPAL = {
    MAKE_PAYMENT_REQUEST: 'MAKE_PAYMENT_REQUEST',
    MAKE_PAYMENT_SUCCESS: 'MAKE_PAYMENT_SUCCESS',
    MAKE_PAYMENT_ERROR: 'MAKE_PAYMENT_ERROR',

    CLEAR_PAYMENT_VALUES: 'CLEAR_PAYMENT_VALUES',
    CLEAR_PAYMENT_ERROR: 'CLEAR_PAYMENT_ERROR'
}